---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: elasticsearch
    run_list:
      - recipe[aps-elasticsearch::default]
    verifier:
      inspec_tests:
        - name: ES-checks
          path: test/integration/elasticsearch/inspec
