---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: elasticsearch
    run_list:
      - recipe[aps-elasticsearch::default]
    verifier:
      inspec_tests:
        - name: ES-checks
          path: test/integration/elasticsearch/inspec
    attributes: {
      "name": "chef-aps-elasticsearch",
      "hostname": "chef-aps-elasticsearch-test",
      "aps-es" : {
        "unicast_enabled" : false,
        "multicast_enabled" : false,
        "ec2_discovery_enabled" : true
        "number_of_shards" : '1',
        "number_of_replicas" : '0',
        "plugin" :
          {
            "cloud-aws" : true
          }
        },
     }
